# Jekyll config

title: tkal.github.io
description: >- # this means to ignore newlines until "baseurl:"
  OffSec notes, guides etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tkal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tkalahan
github_username:  tkal
repository: tkal/tkal.github.io

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.13.0"

# Site Author
author:
  name             : "Thanos Kalachanis"
  avatar           : /assets/img/profile.png
  bio              : "Red Team Ops"
  location         : "::1"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  github           : tkal
  linkedin         : tkalachanis 
  twitter          : tkalahan

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: # true
      share: true
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
related: true

# theme
remote_theme: "mmistakes/minimal-mistakes@4.13.0"

