title: Thanos Kalachanis
description: > # this means to ignore newlines until "baseurl:"
   twitter: <a href="https://twitter.com/tkalahan">@tkalahan</a><br>Website: <a href="https://tkal.github.io/">tkal.github.io</a><br><br><img src="https://raw.githubusercontent.com/tkal/tkal.github.io/master/images/profile.png" alt="MU"><br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-minimal
